version: '3.3'

services:
    back:
        container_name: coffee-manager-back
        image: coffee-manager-back
        build:
            context: docker
            dockerfile: back/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - "./bin:/app/bin"
            - "./lib:/app/lib"
